-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."niconico_user_broadcast_history_responses" add column "response_status_code" integer
--  null;
