-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."niconico_live_programs" add column "remote_niconico_user_id" text
--  not null unique;
