services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      start_period: 10s

  graphql-engine:
    image: hasura/graphql-engine:v2.36.0
    restart: always
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:password@postgres:5432/postgres
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET:?}
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=anonymous
      # https://hasura.io/docs/latest/graphql/core/auth/authentication/jwt.html
      - HASURA_GRAPHQL_JWT_SECRET=${HASURA_GRAPHQL_JWT_SECRET:?}

volumes:
  postgres_data:
