-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."niconico_users" add column "icon_fetched_at" timestamptz
--  null;
