-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."niconico_user_icons" add column "remote_updated_at" timestamptz
--  null;
