-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."niconico_live_programs" add column "niconico_account_id" uuid
--  not null;
