-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."niconico_users" add column "niconico_user_icon_id" uuid
--  null;
