-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."niconico_user_icon_caches" add column "size" integer
--  not null;
